### ISSUE TITLE
签到错误问题！

### ISSUE THREAD

**Issue by chwl66** [qiandao-today/templates#11]
![image](https://user-images.githubusercontent.com/58024471/123084056-4b8f7900-d453-11eb-8a8c-0f0064558ac1.png)
签到出现599错误，这是什么情况呢！网上找了，没整明白，不知道是不是把签到服务器的IP墙了！

**Comment by asdaragon** [comment]
@chwl66 599一般是在路由上搭建的docker的问题，建议用host模式运行，或者开放docker的防火墙。
host 模式参考 https://github.com/AragonSnow/qiandao/issues/67
