### ISSUE TITLE
华为花粉俱乐部签到失败

### ISSUE THREAD

**Issue by 17huiwei** [qiandao-today/templates#139]
Failed at 1/5 request,
Fail assert: {"re": "您需要先登录才能继续本操作", "from": "content"} from failed_asserts,
Response Error : OK,
Request URL: https://club.huawei.com/hwsign-sign.html

总是提示这个信息。

**Comment by acooler15** [comment]
脚本失效了。如果有相关建议或反馈请在 #14 进行
