### ISSUE TITLE
花粉俱乐部 评论区

### ISSUE THREAD

**Issue by AragonSnow** [qiandao-today/templates#14]

**Comment by appotry** [comment]
这个现在失效了？

**Comment by hanxue1205** [comment]
每次都是提示 未登陆

**Comment by github-h** [comment]
来了来了  花粉俱乐部模板其实没问题

是251那边把登录做严格了

**现在要签到框架的IP和UA必须与论坛登录的一致**

得到的cookie才能被框架使用
而且差不多9天到期一次cookie

我自己都懒得搞了真的麻烦

**Comment by github-h** [comment]
花粉俱乐部现在无签到功能了
