### ISSUE TITLE
咨询下各位大大，有个鸿鹄论坛需要帮忙增加下

### ISSUE THREAD

**Issue by feelangel** [qiandao-today/templates#185]
https://github.com/feelangel/templates/blob/master/%E9%B8%BF%E9%B9%84%E8%AE%BA%E5%9D%9B.har

我建了一个测试使用，不过一直有问题，可以帮忙修改测试下么？

2022-03-29 10:25:39
日志：Failed at 1/4 request,
Fail assert: {"re": "您需要先登录才能继续本操作", "from": "content"} from failed_asserts,
Response Error : OK,
Request URL: https://bbs.hh010.com/plugin.php?id=dsu_paulsign%3Asign

**Comment by FellBan** [comment]
已更新
