### ISSUE TITLE
公共模板同步完看不到

### ISSUE THREAD

**Issue by ni7ht** [qiandao-today/templates#198]
![微信截图_20220419233043](https://user-images.githubusercontent.com/37174285/164040660-a59c4843-8650-4226-ada1-c086968c554d.png)

**Comment by a76yyyy** [comment]
通过容器后台日志检查容器是否能获取到jsdelivr的dns，并能与jsdelivr cdn建立连接

**Comment by ni7ht** [comment]
> 通过容器后台日志检查容器是否能获取到jsdelivr的dns，并能与jsdelivr cdn建立连接
感谢回复，看了下还真是不行，我先尝试下自己能搞定不，有类似情况解决的方案提供下嘛？我现在是openwrt跑的docker，目前macvlan，换桥接或者直链host？

stdout: [W 220419 23:18:02 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out -> Try to retry!
stdout: [E 220419 23:18:32 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out
stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/updating/ (192.168.2.15) 58260.26ms
stdout: [E 220419 23:18:33 subscribe:132] UserID: 1 update Subscribe failed! Reason: 
stdout:     打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json
stdout:     
stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 36.08ms
stdout: [I 220419 23:18:49 web:2239] 200 GET /subscribe/signup_repos/1/ (192.168.2.15) 42.58ms
stdout: [I 220419 23:18:53 web:2239] 304 GET /subscribe/1/ (192.168.2.15) 37.87ms
stdout: [I 220419 23:19:12 web:2239] 302 POST /subscribe/refresh/1/?op=clear (192.168.2.15) 28.12ms
stdout: [I 220419 23:19:12 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 42.81ms
stdout: [W 220419 23:19:41 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out -> Try to retry!
stdout: [E 220419 23:20:11 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out
stdout: [I 220419 23:20:11 web:2239] 304 GET /subscribe/1/updating/ (192.168.2.15) 58230.53ms
stdout: [E 220419 23:20:11 subscribe:132] UserID: 1 update Subscribe failed! Reason: 
stdout:     打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json

**Comment by a76yyyy** [comment]
> > 通过容器后台日志检查容器是否能获取到jsdelivr的dns，并能与jsdelivr cdn建立连接
> > 感谢回复，看了下还真是不行，我先尝试下自己能搞定不，有类似情况解决的方案提供下嘛？我现在是openwrt跑的docker，目前macvlan，换桥接或者直链host？
> 
> stdout: [W 220419 23:18:02 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out -> Try to retry! stdout: [E 220419 23:18:32 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/updating/ (192.168.2.15) 58260.26ms stdout: [E 220419 23:18:33 subscribe:132] UserID: 1 update Subscribe failed! Reason: stdout: 打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json stdout: stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 36.08ms stdout: [I 220419 23:18:49 web:2239] 200 GET /subscribe/signup_repos/1/ (192.168.2.15) 42.58ms stdout: [I 220419 23:18:53 web:2239] 304 GET /subscribe/1/ (192.168.2.15) 37.87ms stdout: [I 220419 23:19:12 web:2239] 302 POST /subscribe/refresh/1/?op=clear (192.168.2.15) 28.12ms stdout: [I 220419 23:19:12 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 42.81ms stdout: [W 220419 23:19:41 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out -> Try to retry! stdout: [E 220419 23:20:11 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out stdout: [I 220419 23:20:11 web:2239] 304 GET /subscribe/1/updating/ (192.168.2.15) 58230.53ms stdout: [E 220419 23:20:11 subscribe:132] UserID: 1 update Subscribe failed! Reason: stdout: 打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json

看一下你docker外能不能访问jsdelivr

**Comment by ni7ht** [comment]
> > > 通过容器后台日志检查容器是否能获取到jsdelivr的dns，并能与jsdelivr cdn建立连接
> > > 感谢回复，看了下还真是不行，我先尝试下自己能搞定不，有类似情况解决的方案提供下嘛？我现在是openwrt跑的docker，目前macvlan，换桥接或者直链host？
> > 
> > 
> > stdout: [W 220419 23:18:02 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out -> Try to retry! stdout: [E 220419 23:18:32 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28150 ms: Operation timed out stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/updating/ (192.168.2.15) 58260.26ms stdout: [E 220419 23:18:33 subscribe:132] UserID: 1 update Subscribe failed! Reason: stdout: 打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json stdout: stdout: [I 220419 23:18:33 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 36.08ms stdout: [I 220419 23:18:49 web:2239] 200 GET /subscribe/signup_repos/1/ (192.168.2.15) 42.58ms stdout: [I 220419 23:18:53 web:2239] 304 GET /subscribe/1/ (192.168.2.15) 37.87ms stdout: [I 220419 23:19:12 web:2239] 302 POST /subscribe/refresh/1/?op=clear (192.168.2.15) 28.12ms stdout: [I 220419 23:19:12 web:2239] 200 GET /subscribe/1/ (192.168.2.15) 42.81ms stdout: [W 220419 23:19:41 fetcher:460] GET https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json [Warning] HTTP 599: Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out -> Try to retry! stdout: [E 220419 23:20:11 fetcher:464] Failed to connect to cdn.jsdelivr.net port 443 after 28132 ms: Operation timed out stdout: [I 220419 23:20:11 web:2239] 304 GET /subscribe/1/updating/ (192.168.2.15) 58230.53ms stdout: [E 220419 23:20:11 subscribe:132] UserID: 1 update Subscribe failed! Reason: stdout: 打开链接错误https://cdn.jsdelivr.net/gh/qiandao-today/templates@master/tpls_history.json
> 
> 看一下你docker外能不能访问jsdelivr
搞定啦，桥接就好了。我之后在研究研究macvlan看看咋回事。

**Comment by UnicornUnderMoon** [comment]
同样遇到这个问题，反代服务器是apache，版本2.4.58，系统ubuntu 24.04。
使用以下2.4.47版本的方法，故障解除。需新增开启与websocket相关的`mod_proxy_wstunnel`模块。
以下方法[在此](https://github.com/dani-garcia/vaultwarden/discussions/3598)找到：
### Apache HTTP Server >= 2.4.47
`ProxyPass / http://localhost:8888/ upgrade=websocket`
`ProxyPassReverse / http://localhost:8888/ upgrade=websocket`
### Apache HTTP Server < 2.4.47
```
ProxyPass / http://localhost:8888/
RewriteEngine   on
RewriteCond     %{HTTP:Upgrade}       websocket                   [NC]
RewriteCond     %{HTTP:Connection}    upgrade                     [NC]
RewriteRule     ^/?(.*)               "ws://localhost:8888/$1"    [P,L]
```
