### ISSUE TITLE
速蛙云 评论区

### ISSUE THREAD

**Issue by a76yyyy** [qiandao-today/templates#206]

**Comment by Sh7ne** [comment]
上传就直接卡住了。。。。

**Comment by a76yyyy** [comment]
不是可以在框架的公共模板库里直接订阅么

**Comment by Sh7ne** [comment]
> > 上传就直接卡住了。。。。
> 
> 
> 
> 不是可以在框架的公共模板库里直接订阅么

自己docker里跑的

**Comment by a76yyyy** [comment]
> > > 上传就直接卡住了。。。。
> > 
> > 
> > 不是可以在框架的公共模板库里直接订阅么
> 
> 自己docker里跑的

自己的容器也可以订阅公共模板库的
![image](https://user-images.githubusercontent.com/56478790/174713669-a10441e7-3528-40c6-994b-60d2071c7252.png)

![image](https://user-images.githubusercontent.com/56478790/174713963-df33d66d-0da7-460c-8039-4ade33fe850f.png)

**Comment by wjw054509** [comment]
这两天好像使用不了，一直失败

**Comment by 17huiwei** [comment]
速蛙云老是被封

**Comment by 17huiwei** [comment]
已经跑路了，可以删除了……

**Comment by Sh7ne** [comment]
> 已经跑路了，可以删除了……

是的 XTMS
