### ISSUE TITLE
哔哩哔哩脚本失效

### ISSUE THREAD

**Issue by li828702** [qiandao-today/templates#320]
- 名称：哔哩哔哩
- 类型：网站
- 网址：https://www.bilibili.com/
- 相关：之前的脚步今天失效了
- 描述：报错信息：<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.22.1</center> </body> </html>      
```

**Comment by chen8945** [comment]
请修改 nginx 的超时时间，具体方法可使用搜索引擎搜索`504 Gateway Time-out`，或者自行将脚本中的延时降低或删除
