### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by ijimmytalon** [qiandao-today/templates#323]
Failed at 2/3 request,
Fail assert: {"re": "200", "from": "status"} from success_asserts,
Response Error : HTTP 400: Bad Request,
Request URL: https://invites.fun/api/users/{{uid}}

**Comment by github-h** [comment]
请在正确的issue内反馈 https://github.com/qiandao-today/templates/issues/315

> Failed at 2/3 request, Fail assert: {"re": "200", "from": "status"} from success_asserts, Response Error : HTTP 400: Bad Request, Request URL: [https://invites.fun/api/users/{{uid}}](https://invites.fun/api/users/%7B%7Buid%7D%7D)
