### ISSUE TITLE
有制作模板需求的，请提交在这里。

### ISSUE THREAD

**Issue by KiteMJ** [qiandao-today/templates#332]
- 名称：cordc
- 类型：网站
- 网址：https://www.cordc.xyz/
- 相关：无
- 描述：签到领流量有返回领取多少流量即可
邀请注册链接：https://www.cordc.net/auth/register?code=jPDC

**Comment by IScRYM** [comment]
名称：老王论坛
    类型：网站
    网址：http://laowang.vip
    相关：无
    描述：签到领金币
    邀请注册链接：http://ezrw5695ef.xyz:4829/thread-1035923-1-1.html?x=3546784

**Comment by chen8945** [comment]
请前往此处 #171
