### ISSUE TITLE
求模板区

### ISSUE THREAD

**Issue by AragonSnow** [qiandao-today/templates#48]
有制作模板需求的，请提交在这里，要留网站名和链接

**Comment by caliban511** [comment]
求B站签到功能：bilibili.com

**Comment by jimgo188** [comment]
求pt时间签到模板  www.pttime.org  谢谢！

**Comment by gui-li** [comment]
求淘宝淘金币签到，无忧行无忧币签到，京东京豆签到

**Comment by Lee917** [comment]
请求制作【远景论坛】和【卡饭论坛】的签到模板，虽说有脚本https://greasyfork.org/zh-CN/scripts/38018-%E8%87%AA%E7%94%A8%E8%AE%BA%E5%9D%9B%E8%BE%85%E5%8A%A9%E7%AD%BE%E5%88%B0
可以实现，但这需要打开对应站点才能执行，很不方便，希望能制作出模板，然后再软路由上自动执行签到
先说声谢谢！！！

**Comment by Lee917** [comment]
> 请求制作【远景论坛】和【卡饭论坛】的签到模板，虽说有脚本https://greasyfork.org/zh-CN/scripts/38018-%E8%87%AA%E7%94%A8%E8%AE%BA%E5%9D%9B%E8%BE%85%E5%8A%A9%E7%AD%BE%E5%88%B0
> 可以实现，但这需要打开对应站点才能执行，很不方便，希望能制作出模板，然后再软路由上自动执行签到
> 先说声谢谢！！！

远景论坛已经有了，希望也能发布卡饭论坛的签到模板

**Comment by Lee917** [comment]
抱歉，我没注意看置顶的消息
网站名称：卡饭论坛
网站链接：https://bbs.kafan.cn/

**Comment by ln03wen** [comment]
求 Hao4K 的自动签到
网站链接：www.hao4k.cn
网站的签到链接：www.hao4k.cn/qiandao/

**Comment by Ahao09** [comment]
求爱奇艺签到模板
网站链接：https://www.iqiyi.com/

**Comment by 1592554701** [comment]
求更新一下PT柠檬，去年改了网址 T.T

**Comment by jouleken** [comment]
幕后
https://muhou.net/
尝试套用好快的车模板修改，找不到问题出在哪里
感谢

**Comment by chriskong5155** [comment]
网站名称：粤梦缘
网站链接：https://www.dranime.net/
自己试过搞，显示成功，但无效，先谢谢大佬！

**Comment by ChaoHao-14** [comment]
求爱奇艺会员签到+三次抽奖 http://qiyi.com/

**Comment by xysgx** [comment]
求hao4k网站的签到模板
https://www.hao4k.cn/

**Comment by 331969102** [comment]
求微博超话自动签到的模板！！！

**Comment by MR-TQ** [comment]
希望大佬能做个koolshare论坛的模板
koolshare.cn

**Comment by Hydrahail-Johnson** [comment]
网站名称：HDCHINA
网站链接：https://hdchina.org/

**Comment by wangx2** [comment]
网站名：全球主机论坛
网    址：www.hostloc.com

**Comment by wf31244221** [comment]
求https://www.hifini.com/签到，谢谢！

**Comment by wf31244221** [comment]
求 https://www.hifini.com/    签到，谢谢大佬！

**Comment by zhaobuxuan2021** [comment]
https://www.iamtxt.com/求这个，电子书的。
http://www.peiyin.net/bbs/index.php?m=bbs求这个，电影的。
https://en5556.com/plugin.php?id=dc_signin求这个，英语资源的。

**Comment by dvdrm** [comment]
求好书有签到及领取银币，
网站名称：好书有论坛
网站链接：https://www.93hsy.com/

**Comment by Coolrui1816** [comment]
> 求爱奇艺会员签到+三次抽奖http://qiyi.com/

GitHub里面现成的很多啊。。

**Comment by wildbooks** [comment]
求百度贴吧模板

**Comment by wangzhili888** [comment]
求c机械工程师网的签到模板
https://www.swbbsc.com/

**Comment by jvc2025** [comment]
网站名称：琵琶行
网站链接：https://www.ppxclub.com/

**Comment by ccav678** [comment]
网站名：琵琶行
网 址：https://www.ppxclub.com/

**Comment by ddd-zero** [comment]
> 求pt时间签到模板 [www.pttime.org](http://www.pttime.org) 谢谢！

[PT签到模板.zip](https://github.com/qiandao-today/templates/files/7034272/PT.zip)

用这个PT 通用模板，cookie的，网址填https://www.pttime.org/（其他PT站同理！请务必带上 https:// 及其最后的 / ）
[机场模板.zip](https://github.com/qiandao-today/templates/files/7034286/default.zip)
再传一个机场通用签到模板，账号密码版本的，原理 网址 同上

**Comment by acooler15** [comment]
> 求BT吧 签到模板 https://www.aibtba.com/ 谢谢

这个网站的签到好像只需要cookie里的`bt_nickname`和`bt_user_id`就可以，
当然因为登录没有验证，也可以使用帐号和密码，就是不知道每天都登录会不会被ban。。。
```
  curl 'https://u.aibtba.com/sign?x=1&y=1&search_referer=&callback=Json' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: "Microsoft Edge";v="93", " Not;A Brand";v="99", "Chromium";v="93"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.44' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Accept: */*' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: no-cors' \
  -H 'Sec-Fetch-Dest: script' \
  -H 'Referer: https://www.aibtba.com/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'Cookie: bt_nickname=xxx; bt_user_id=012345678901;'
  ```

**Comment by ln03wen** [comment]
求一酷网签到模板，不胜感激。https://c4dco.com/user

**Comment by liujixu1984** [comment]
求

https://wangzi.uk
https://a.luxury 

这两个机场的模板

**Comment by windmaster-pt** [comment]
求淘宝淘金币和种水果模版https://taojinbi.taobao.com/index.htm?spm=a21bo.21814703.201864-1.d2.5af911d9NMe49V&auto_take=true
求京东领京豆和种水果模版https://bean.jd.com/myJingBean/list#earnBean

**Comment by leeuuu** [comment]
联想社区论坛
https://club.lenovo.com.cn/
